Fixing post issue

diff --git a/.github/workflows/deploy-to-ec2.yml b/.github/workflows/deploy-to-ec2.yml
--- a/.github/workflows/deploy-to-ec2.yml
+++ b/.github/workflows/deploy-to-ec2.yml
@@ -78,6 +78,7 @@ jobs:
       - name: SSH into EC2 instance and start Spring Boot app
         run: |
           ssh -o StrictHostKeyChecking=no -f -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST_DNS }} "nohup java -jar target/$JAR_FILE --spring.profiles.active=prod &"
+
   health-check:
     name: Verify the app is live
     runs-on: ubuntu-latest
@@ -87,6 +88,12 @@ jobs:
         run: sleep 60
         shell: bash
 
-      - name: Hit the endpoint
+      - name: Hit the endpoint and check status code
         run: |
-          curl --location --insecure 'https://web-service.johnchoi96.com/api/test/ping'
+          HTTP_STATUS=$(curl --write-out "%{http_code}" --silent --output /dev/null 'https://web-service.johnchoi96.com/api/test/ping')
+          if [ "$HTTP_STATUS" -ne 200 ]; then
+            echo "Health check failed with status code: $HTTP_STATUS"
+            exit 1
+          else
+            echo "Health check passed with status code: $HTTP_STATUS"
+          fi
